### PR TITLE
Fix issue #9: add second pattern-matching for outlet parsing

### PR DESCRIPTION
**Pull request by CharlesB2**
It seems that APC versions can differ in their output, this PR handles two different forms of outlet printing

### CODE REVIEW

**Comment by scls19fr** [comment]
Closes #9

**Comment by scls19fr** [comment]
Thanks @CharlesB2 for this nice contribution.

**Comment by scls19fr** [comment]
but I can't merge because CI is failing (I'm using protected master branch).
Could you have a look?

**Comment by scls19fr** [comment]
The problem seems to be about PEP8
See https://travis-ci.com/scls19fr/APC/builds/128819861#L304

**Comment by CharlesB2** [comment]
Fixed it (Travis CI was actually already failing :) )

**Comment by scls19fr** [comment]
Closes #11 

Thanks @CharlesB2 for your contribution!

**Pull request merged**
